### ISSUE TITLE
Factorizing 97020

### ISSUE THREAD

**Issue by timvermeulen** [phillip-h/reikna#1]
My program seems to enter an endless loop if I call `reikna::factor::quick_factorize(97020)`, an internal call to `rho(45, 2)` seems to be causing it. I don't understand the algorithm well enough to know how to fix it, unfortunately.

**Comment by josephlr** [comment]
I also hit this with `quick_factorize_wsp(103685, &sprimes)`

**Comment by phillip-h** [comment]
Apologies for leaving this open for so long, should be resolved by commit 2fe5a2e. Essentially the function was not properly handling a failure of the rho algorithm which should have resulted in a re-run with different initial values. 97020 and 103685 both correctly factorize now. Changes should be up on cargo too.

If it wasn't clear, I'm not actively working on this project (or with Rust in general). I'll keep trying to respond to any issues that come in, however. I've noted this in the readme as well now.
